
FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./

RUN yarn install

ENV NODE_ENV=production

COPY . .
RUN yarn build


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./

RUN yarn install

COPY --from=builder /app/dist ./dist
COPY .env.production ./.env.production

EXPOSE 3000

CMD ["node", "dist/app/api.js"]
