FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install

COPY . .
RUN yarn build


FROM node:22-alpine AS runner

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/app/api.js"]
